import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# CogniSync: Final CIKM Evaluation & Significance Suite\n",
                "\n",
                "This notebook is optimized for **Google Colab (T4 GPU)**. It runs all the rigorous statistical ablations required for the final CIKM rebuttal, including:\n",
                "1. **Security Ablation**: Classifier vs. Classifier + Goal-Redirection.\n",
                "2. **Full-Corpus Significance**: Wilcoxon signed-rank test on the computed margin (100K distractor corpus).\n",
                "3. **Hybrid Component Ablation**: Disentangling Learned-Alpha fusion from Cross-Encoder reranking (with Bonferroni corrections and 95% CIs). Uses dynamic 50-document candidate pools to strictly isolate retrieval gains.\n",
                "\n",
                "All raw results and per-query scores are saved to the `/content/cognisync_results` directory."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 0. Install Dependencies\n",
                "!pip install datasets faiss-cpu rank_bm25 sentence-transformers scikit-learn pandas numpy scipy tqdm --quiet\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Environment & Global Setup\n",
                "import os\n",
                "import random\n",
                "import time\n",
                "import json\n",
                "import hashlib\n",
                "import re\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "from tqdm import tqdm\n",
                "from scipy import stats\n",
                "import faiss\n",
                "import torch\n",
                "from rank_bm25 import BM25Okapi\n",
                "from datasets import load_dataset\n",
                "from sentence_transformers import SentenceTransformer, CrossEncoder\n",
                "from sklearn.ensemble import RandomForestRegressor\n",
                "from sklearn.linear_model import LogisticRegression\n",
                "from sklearn.model_selection import train_test_split\n",
                "from sklearn.metrics import classification_report, f1_score\n",
                "\n",
                "RANDOM_SEED = 42\n",
                "random.seed(RANDOM_SEED)\n",
                "np.random.seed(RANDOM_SEED)\n",
                "\n",
                "OUTPUT_DIR = '/content/cognisync_results'\n",
                "os.makedirs(f'{OUTPUT_DIR}/results', exist_ok=True)\n",
                "os.makedirs(f'{OUTPUT_DIR}/logs', exist_ok=True)\n",
                "\n",
                "print(\"CUDA Available:\", torch.cuda.is_available())\n",
                "DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
                "MODEL_NAME = 'sentence-transformers/all-MiniLM-L6-v2'\n",
                "ENCODER = SentenceTransformer(MODEL_NAME).to(DEVICE)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Security Component Ablation\n",
                "print(\"\\n================ 1. SECURITY ABLATION ================\")\n",
                "class MultiSignalDefense:\n",
                "    def __init__(self, encoder):\n",
                "        self.encoder = encoder\n",
                "        self.classifier = None\n",
                "        self.mean_clean_emb = None\n",
                "        self.clean_docs = None\n",
                "\n",
                "    def fit(self, clean_docs, ds):\n",
                "        self.clean_docs = list(clean_docs)\n",
                "        clean_embs = self.encoder.encode(self.clean_docs, show_progress_bar=False, batch_size=256)\n",
                "        mean_emb = np.mean(clean_embs, axis=0)\n",
                "        self.mean_clean_emb = mean_emb / (np.linalg.norm(mean_emb) + 1e-10)\n",
                "        \n",
                "        df = ds.to_pandas()\n",
                "        X_texts = df['text'].tolist()\n",
                "        y_true = df['label'].tolist()\n",
                "        \n",
                "        X_embs = self.encoder.encode(X_texts, show_progress_bar=False, batch_size=256)\n",
                "        X_train, X_test, y_train, y_test = train_test_split(X_embs, y_true, test_size=0.2, random_state=RANDOM_SEED, stratify=y_true)\n",
                "        \n",
                "        self.classifier = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=RANDOM_SEED)\n",
                "        self.classifier.fit(X_train, y_train)\n",
                "        return self, X_test, y_test\n",
                "\n",
                "    def filter_full_heuristic(self, query, candidate_docs):\n",
                "        if not candidate_docs: return [], []\n",
                "        embs = self.encoder.encode(candidate_docs, show_progress_bar=False, batch_size=256)\n",
                "        q_emb = self.encoder.encode([query], show_progress_bar=False)[0]\n",
                "        q_norm = q_emb / (np.linalg.norm(q_emb) + 1e-10)\n",
                "        preds = self.classifier.predict_proba(embs)[:, 1]\n",
                "        \n",
                "        filtered_indices, blocked_indices = [], []\n",
                "        for i, (doc, prob) in enumerate(zip(candidate_docs, preds)):\n",
                "            norm_emb = embs[i] / (np.linalg.norm(embs[i]) + 1e-10)\n",
                "            q_sim = np.dot(norm_emb, q_norm)\n",
                "            imperative = 1.0 if re.search(r'(?i)\\b(ignore|reveal|execute|forget|bypass|output)\\b', doc) else 0.0\n",
                "            is_goal_redirection = (imperative > 0) and (q_sim < 0.3)\n",
                "            \n",
                "            if prob < 0.5 and not is_goal_redirection:\n",
                "                filtered_indices.append(i)\n",
                "            else:\n",
                "                blocked_indices.append(i)\n",
                "        return filtered_indices, blocked_indices\n",
                "\n",
                "ds_sec = load_dataset(\"deepset/prompt-injections\", split=\"train\")\n",
                "total_samples = len(ds_sec)\n",
                "benign_count = sum(1 for x in ds_sec if x['label'] == 0)\n",
                "malicious_count = total_samples - benign_count\n",
                "print(f\"Dataset Counts -> Benign: {benign_count}, Malicious: {malicious_count}\")\n",
                "\n",
                "defense = MultiSignalDefense(ENCODER)\n",
                "clean_pool = [x['text'] for x in ds_sec if x['label'] == 0][:100]\n",
                "defense, X_test, y_test = defense.fit(clean_pool, ds_sec)\n",
                "\n",
                "preds_clf = defense.classifier.predict(X_test)\n",
                "report_clf = classification_report(y_test, preds_clf, output_dict=True)\n",
                "\n",
                "df_sec = ds_sec.to_pandas()\n",
                "_, X_test_texts, _, y_test_labels = train_test_split(df_sec['text'].tolist(), df_sec['label'].tolist(), test_size=0.2, random_state=RANDOM_SEED, stratify=df_sec['label'].tolist())\n",
                "\n",
                "user_query = \"What is the capital of France?\"\n",
                "_, blocked_indices_heuristic = defense.filter_full_heuristic(user_query, X_test_texts)\n",
                "preds_heur = [1 if i in blocked_indices_heuristic else 0 for i in range(len(X_test_texts))]\n",
                "report_heur = classification_report(y_test_labels, preds_heur, output_dict=True)\n",
                "\n",
                "sec_results = [\n",
                "    {\"Variant\": \"Classifier Only\", \"Benign F1\": report_clf['0']['f1-score'], \"Malicious F1\": report_clf['1']['f1-score'], \"Macro F1\": report_clf['macro avg']['f1-score']},\n",
                "    {\"Variant\": \"Classifier + Goal-Redirection Heuristic\", \"Benign F1\": report_heur['0']['f1-score'], \"Malicious F1\": report_heur['1']['f1-score'], \"Macro F1\": report_heur['macro avg']['f1-score']}\n",
                "]\n",
                "pd.DataFrame(sec_results).to_csv(f\"{OUTPUT_DIR}/results/security_ablation_metrics.csv\", index=False)\n",
                "print(pd.DataFrame(sec_results).to_string())\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Full-Corpus Significance Test\n",
                "print(\"\\n================ 2. FULL-CORPUS SIGNIFICANCE ================\")\n",
                "class PersistentHybridIndex:\n",
                "    def __init__(self, encoder):\n",
                "        self.encoder = encoder\n",
                "        self.faiss_index = None\n",
                "        self.bm25 = None\n",
                "        self.doc_store = []\n",
                "        \n",
                "    def build(self, documents, batch_size=512):\n",
                "        self.doc_store = documents\n",
                "        embs = self.encoder.encode(documents, show_progress_bar=True, batch_size=batch_size)\n",
                "        faiss.normalize_L2(embs)\n",
                "        self.faiss_index = faiss.IndexFlatIP(embs.shape[1])\n",
                "        self.faiss_index.add(embs)\n",
                "        \n",
                "        tokenized = [doc.split() for doc in tqdm(documents, desc=\"Tokenizing for BM25\")]\n",
                "        self.bm25 = BM25Okapi(tokenized)\n",
                "        \n",
                "    def retrieve(self, query, top_k=100, alpha=0.6):\n",
                "        q_emb = self.encoder.encode([query], show_progress_bar=False)\n",
                "        faiss.normalize_L2(q_emb)\n",
                "        d_scores, d_idx = self.faiss_index.search(q_emb, top_k * 2)\n",
                "        \n",
                "        b_scores = self.bm25.get_scores(query.split())\n",
                "        b_idx = np.argsort(b_scores)[::-1][:top_k * 2]\n",
                "        \n",
                "        dense_norm = {idx: (d_scores[0][i] - np.min(d_scores[0])) / (np.max(d_scores[0]) - np.min(d_scores[0]) + 1e-10) for i, idx in enumerate(d_idx[0])}\n",
                "        b_rel_scores = [b_scores[i] for i in b_idx]\n",
                "        b_min, b_max = np.min(b_rel_scores), np.max(b_rel_scores)\n",
                "        bm25_norm = {idx: (b_scores[idx] - b_min) / (b_max - b_min + 1e-10) for idx in b_idx}\n",
                "        \n",
                "        fusion_scores = {}\n",
                "        for idx in set(d_idx[0]) | set(b_idx):\n",
                "            fusion_scores[idx] = alpha * dense_norm.get(idx, 0.0) + (1 - alpha) * bm25_norm.get(idx, 0.0)\n",
                "            \n",
                "        ranked = sorted(fusion_scores.keys(), key=lambda x: fusion_scores[x], reverse=True)[:top_k]\n",
                "        dense_only = list(d_idx[0])[:top_k]\n",
                "        return ranked, dense_only\n",
                "\n",
                "print(\"Loading 100K MS MARCO Corpus...\")\n",
                "marco_ds = load_dataset('Tevatron/msmarco-passage-corpus', split='train')\n",
                "marco_subset = marco_ds.select(range(100000))\n",
                "marco_queries = load_dataset('Tevatron/msmarco-passage', split='train')\n",
                "q_subset = marco_queries.select(range(500))\n",
                "\n",
                "documents = list(marco_subset['text'])\n",
                "all_docids = list(marco_subset['docid'])\n",
                "\n",
                "for item in q_subset:\n",
                "    for p in item['positive_passages']:\n",
                "        if p['docid'] not in all_docids:\n",
                "            documents.append(p['text'])\n",
                "            all_docids.append(p['docid'])\n",
                "\n",
                "hybrid_index = PersistentHybridIndex(ENCODER)\n",
                "hybrid_index.build(documents)\n",
                "\n",
                "docid_to_idx = {str(docid): i for i, docid in enumerate(all_docids)}\n",
                "eval_queries = []\n",
                "for item in q_subset:\n",
                "    pos_docids = [str(p['docid']) for p in item['positive_passages']]\n",
                "    valid_idxs = [docid_to_idx[did] for did in pos_docids if did in docid_to_idx]\n",
                "    if valid_idxs: eval_queries.append((item['query'], valid_idxs))\n",
                "\n",
                "mrr_hybrid, mrr_dense = [], []\n",
                "for q, rel_idxs in tqdm(eval_queries, desc=\"Evaluating 500 Queries\"):\n",
                "    ranked_hybrid, ranked_dense = hybrid_index.retrieve(q, top_k=10, alpha=0.6)\n",
                "    h_mrr = next((1.0 / (r + 1) for r, idx in enumerate(ranked_hybrid) if idx in rel_idxs), 0.0)\n",
                "    d_mrr = next((1.0 / (r + 1) for r, idx in enumerate(ranked_dense) if idx in rel_idxs), 0.0)\n",
                "    mrr_hybrid.append(h_mrr)\n",
                "    mrr_dense.append(d_mrr)\n",
                "\n",
                "pd.DataFrame({\"Query_ID\": range(len(eval_queries)), \"MRR_Hybrid\": mrr_hybrid, \"MRR_Dense\": mrr_dense}).to_csv(f\"{OUTPUT_DIR}/results/full_corpus_raw_mrr.csv\", index=False)\n",
                "\n",
                "mean_hybrid, mean_dense = np.mean(mrr_hybrid), np.mean(mrr_dense)\n",
                "print(f\"Hybrid MRR@10: {mean_hybrid:.4f} | Dense MRR@10: {mean_dense:.4f}\")\n",
                "if np.all(np.array(mrr_hybrid) - np.array(mrr_dense) == 0):\n",
                "    print(\"No difference. p-value = 1.0\")\n",
                "else:\n",
                "    stat, p_val = stats.wilcoxon(mrr_hybrid, mrr_dense, alternative='two-sided')\n",
                "    print(f\"Wilcoxon signed-rank test p-value: {p_val:.4g}\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Fusion vs. Cross-Encoder Reranker Ablation\n",
                "print(\"\\n================ 3. COMPONENT ABLATION ================\")\n",
                "CROSS_ENCODER = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2', max_length=512, device=DEVICE)\n",
                "\n",
                "def unique_preserve_order(values):\n",
                "    seen = set(); out = []\n",
                "    for v in values:\n",
                "        if v and str(v) not in seen: seen.add(str(v)); out.append(str(v))\n",
                "    return out\n",
                "\n",
                "def compute_mrr(retrieved, relevant, k=5):\n",
                "    for rank, idx in enumerate(retrieved[:k]):\n",
                "        if idx in relevant: return 1.0 / (rank + 1)\n",
                "    return 0.0\n",
                "\n",
                "class AblationSystem:\n",
                "    def extract_features(self, query, documents):\n",
                "        unique_docs = list(dict.fromkeys(documents))\n",
                "        unique_embeddings = ENCODER.encode(unique_docs, show_progress_bar=False, batch_size=256)\n",
                "        embedding_by_doc = dict(zip(unique_docs, unique_embeddings))\n",
                "        doc_embeddings = np.vstack([embedding_by_doc[doc] for doc in documents])\n",
                "        \n",
                "        query_embedding = ENCODER.encode([query], show_progress_bar=False)\n",
                "        faiss.normalize_L2(doc_embeddings)\n",
                "        faiss.normalize_L2(query_embedding)\n",
                "        cpu_index = faiss.IndexFlatIP(doc_embeddings.shape[1])\n",
                "        cpu_index.add(doc_embeddings)\n",
                "        dense_scores_raw, dense_indices = cpu_index.search(query_embedding, len(documents))\n",
                "        dense_full = [int(i) for i in dense_indices[0]]\n",
                "        dense_sim = np.zeros(len(documents))\n",
                "        for r, idx in enumerate(dense_full): dense_sim[idx] = float(dense_scores_raw[0][r])\n",
                "        \n",
                "        tokenized_docs = [doc.split() for doc in documents]\n",
                "        bm25 = BM25Okapi(tokenized_docs)\n",
                "        bm25_scores = bm25.get_scores(query.split())\n",
                "        \n",
                "        d_min, d_max = float(np.min(dense_sim)), float(np.max(dense_sim))\n",
                "        b_min, b_max = float(np.min(bm25_scores)), float(np.max(bm25_scores))\n",
                "        norm_dense = (dense_sim - d_min) / (d_max - d_min + 1e-10)\n",
                "        norm_bm25 = (bm25_scores - b_min) / (b_max - b_min + 1e-10)\n",
                "        \n",
                "        q_len = len(query.split())\n",
                "        has_id = 1.0 if re.search(r'\\b(id|uuid|hash|key)\\b', query, re.IGNORECASE) else 0.0\n",
                "        features = [q_len, float(np.std(norm_dense)), float(np.std(norm_bm25)), \n",
                "                    float(np.std(norm_dense)) / (float(np.mean(norm_dense)) + 1e-10), \n",
                "                    float(np.std(norm_bm25)) / (float(np.mean(norm_bm25)) + 1e-10), has_id]\n",
                "        return features, norm_dense, norm_bm25, dense_full, dense_sim, bm25_scores\n",
                "\n",
                "    def retrieve_ablations(self, query, documents, alpha_model):\n",
                "        features, norm_dense, norm_bm25, dense_full, dense_sim, bm25_scores = self.extract_features(query, documents)\n",
                "        lex_full = [int(i) for i in np.argsort(bm25_scores)[::-1]]\n",
                "        dense_ranks = {idx: rank for rank, idx in enumerate(dense_full)}\n",
                "        lex_ranks = {idx: rank for rank, idx in enumerate(lex_full)}\n",
                "\n",
                "        hybrid_scores = {idx: (1 / (60 + dense_ranks.get(idx, len(documents)) + 1)) + (1 / (60 + lex_ranks.get(idx, len(documents)) + 1)) for idx in range(len(documents))}\n",
                "        hybrid_full = sorted(hybrid_scores.keys(), key=lambda x: hybrid_scores[x], reverse=True)\n",
                "\n",
                "        alpha = float(alpha_model.predict([features])[0])\n",
                "        if float(np.max(dense_sim)) > 0.85 or features[4] < 0.1: alpha = 1.0\n",
                "\n",
                "        adaptive_scores = {idx: alpha * norm_dense[idx] + (1 - alpha) * norm_bm25[idx] for idx in range(len(documents))}\n",
                "        adaptive_full = sorted(adaptive_scores.keys(), key=lambda x: adaptive_scores[x], reverse=True)\n",
                "\n",
                "        def rerank(candidates):\n",
                "            top_n = min(10, len(candidates))\n",
                "            if top_n > 1:\n",
                "                ce_scores = CROSS_ENCODER.predict([[query, documents[idx]] for idx in candidates[:top_n]], show_progress_bar=False)\n",
                "                c_scores = {idx: score for idx, score in zip(candidates[:top_n], ce_scores)}\n",
                "                return sorted(c_scores.keys(), key=lambda x: c_scores[x], reverse=True) + candidates[top_n:]\n",
                "            return candidates\n",
                "\n",
                "        return {'Dense': dense_full, 'Sparse': lex_full, 'Naive RRF': hybrid_full, \n",
                "                'Dense + CE': rerank(dense_full), 'Naive RRF + CE': rerank(hybrid_full), \n",
                "                'Learned-Alpha Only': adaptive_full, 'CogniSync Full': rerank(adaptive_full)}\n",
                "\n",
                "print(\"Loading ms_marco validation subset (6,980 queries)...\")\n",
                "ds_ab = load_dataset('microsoft/ms_marco', 'v1.1', split='validation').shuffle(seed=RANDOM_SEED)\n",
                "print(\"Building global distractor pool from first 10K items...\")\n",
                "global_distractors = []\n",
                "for item in tqdm(ds_ab.select(range(10000)), desc=\"Extracting distractors\"):\n",
                "    global_distractors.extend(item.get('passages', {}).get('passage_text', []))\n",
                "global_distractors = list(set(global_distractors))\n",
                "\n",
                "raw = []\n",
                "for item in tqdm(ds_ab.select(range(6980)), desc=\"Building Candidate Pools\"):\n",
                "    q = str(item.get('query', '')).strip()\n",
                "    docs = item.get('passages', {}).get('passage_text', [])\n",
                "    selected = item.get('passages', {}).get('is_selected', [])\n",
                "    rel_idxs = [i for i, f in enumerate(selected) if f == 1]\n",
                "    if not q or not docs or not rel_idxs: continue\n",
                "    u_docs = unique_preserve_order(docs)\n",
                "    distractors = random.sample(global_distractors, 40)\n",
                "    u_docs.extend([d for d in distractors if d not in u_docs])\n",
                "    r_idxs = sorted(set([u_docs.index(str(docs[i])) for i in rel_idxs if str(docs[i]) in u_docs]))\n",
                "    if r_idxs: raw.append({'query': q, 'documents': u_docs, 'relevant_indices': r_idxs})\n",
                "\n",
                "tuning_set, test_set = train_test_split(raw, test_size=0.85, random_state=RANDOM_SEED)\n",
                "ab_sys = AblationSystem()\n",
                "\n",
                "print(f\"Training Regressor on {len(tuning_set)} queries...\")\n",
                "X, y = [], []\n",
                "for item in tuning_set[:300]:\n",
                "    feats, n_d, n_b, _, _, _ = ab_sys.extract_features(item['query'], item['documents'])\n",
                "    b_alpha, b_mrr = 0.5, -1.0\n",
                "    for a in np.linspace(0.0, 1.0, 11):\n",
                "        r = sorted(range(len(item['documents'])), key=lambda i: a * n_d[i] + (1 - a) * n_b[i], reverse=True)\n",
                "        m = compute_mrr(r, set(item['relevant_indices']))\n",
                "        if m > b_mrr: b_mrr, b_alpha = m, a\n",
                "    X.append(feats); y.append(b_alpha)\n",
                "\n",
                "rf = RandomForestRegressor(n_estimators=50, max_depth=5, random_state=RANDOM_SEED).fit(X, y)\n",
                "\n",
                "results = {k: [] for k in ['Dense', 'Sparse', 'Naive RRF', 'Dense + CE', 'Naive RRF + CE', 'Learned-Alpha Only', 'CogniSync Full']}\n",
                "raw_ablation_records = []\n",
                "for i, item in enumerate(tqdm(test_set, desc=\"Evaluating Variants\")):\n",
                "    ranks = ab_sys.retrieve_ablations(item['query'], item['documents'], rf)\n",
                "    if ranks:\n",
                "        row = {\"Query_ID\": i}\n",
                "        for k, v in ranks.items():\n",
                "            m = compute_mrr(v, item['relevant_indices'])\n",
                "            results[k].append(m)\n",
                "            row[k] = m\n",
                "        raw_ablation_records.append(row)\n",
                "\n",
                "pd.DataFrame(raw_ablation_records).to_csv(f\"{OUTPUT_DIR}/results/ablation_raw_mrr_scores.csv\", index=False)\n",
                "\n",
                "stats_recs = []\n",
                "base = np.array(results['CogniSync Full'])\n",
                "for v, scores in results.items():\n",
                "    arr = np.array(scores)\n",
                "    p = 1.0 if v == 'CogniSync Full' or np.all(arr - base == 0) else stats.wilcoxon(arr, base, alternative='two-sided')[1]\n",
                "    bs_means = [np.mean(np.random.choice(arr, size=len(arr), replace=True)) for _ in range(1000)]\n",
                "    stats_recs.append({\"Variant\": v, \"MRR@5\": np.mean(arr), \"95% CI Lower\": np.percentile(bs_means, 2.5), \"95% CI Upper\": np.percentile(bs_means, 97.5), \"Wilcoxon p-value\": p})\n",
                "\n",
                "df_stats = pd.DataFrame(stats_recs)\n",
                "df_stats.to_csv(f\"{OUTPUT_DIR}/results/ablation_fusion_stats.csv\", index=False)\n",
                "print(df_stats.to_string())\n"
            ]
        }
    ],
    "metadata": {},
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(r"c:\Users\msaur\OneDrive\Desktop\Obsidian\obsidian\Faraday\CogniSync_Final_CIKM_Ablations.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)

print("Notebook generated successfully.")