#!/usr/bin/env python3
"""Pre-submission checks for the manuscript that do not need a LaTeX install.

Catches the failures that cost the most time when they surface in latexmk:
missing citation keys, \\input targets that no notebook produces, dangling
\\ref labels, undefined macros, unbalanced braces, and unescaped percent signs.

    python3 lint_paper.py cognisync_tmlr.tex
"""
import re
import sys
from pathlib import Path

TEX = Path(sys.argv[1] if len(sys.argv) > 1 else "cognisync_tmlr.tex")
BIB = TEX.with_suffix(".bib")

# Written by NB6 into ART/paper/. Not expected to exist before the notebooks run.
GENERATED = {
    "tab_main_retrieval.tex", "tab_alpha_policies.tex", "tab_alpha_predictability.tex",
    "tab_attack_defense.tex", "tab_utility_cost.tex", "tab_behavioural_gap.tex",
    "tab_cost.tex", "results_macros.tex",
    "fig_alpha_headroom.pdf", "fig_attack_defense_matrix.pdf",
    "fig_behavioural_asr.pdf", "fig_cost_quality.pdf",
}

problems, notes = [], []


def strip_comments(text):
    """Remove LaTeX comments, respecting escaped percent signs."""
    out = []
    for line in text.splitlines():
        buf = []
        for i, ch in enumerate(line):
            if ch == "%" and (i == 0 or line[i - 1] != "\\"):
                break
            buf.append(ch)
        out.append("".join(buf))
    return "\n".join(out)


if not TEX.exists():
    sys.exit(f"{TEX} not found")
raw = TEX.read_text()
src = strip_comments(raw)

# ---------------------------------------------------------------- citations
cited = set()
for m in re.finditer(r"\\cite[a-z]*\{([^}]*)\}", src):
    cited.update(k.strip() for k in m.group(1).split(","))
defined = set()
if BIB.exists():
    defined = {m.group(1).strip() for m in
               re.finditer(r"@\w+\s*\{\s*([^,\s]+)\s*,", BIB.read_text())}
else:
    problems.append(f"bibliography {BIB.name} not found")
for k in sorted(cited - defined):
    problems.append(f"\\cite{{{k}}} has no entry in {BIB.name}")
for k in sorted(defined - cited):
    notes.append(f"{k} is in the .bib but never cited")

# ------------------------------------------------------------------ inputs
for m in re.finditer(r"\\input\{([^}]*)\}", src):
    tgt = m.group(1)
    fn = tgt if tgt.endswith(".tex") else tgt + ".tex"
    if fn not in GENERATED and not (TEX.parent / fn).exists():
        problems.append(f"\\input{{{tgt}}} is neither generated by NB6 nor present on disk")
for m in re.finditer(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]*)\}", src):
    tgt = m.group(1)
    if tgt not in GENERATED and not (TEX.parent / tgt).exists():
        problems.append(f"\\includegraphics{{{tgt}}} is neither generated by NB6 nor present")

# -------------------------------------------------------------- refs/labels
labels = {m.group(1) for m in re.finditer(r"\\label\{([^}]*)\}", src)}
for m in re.finditer(r"\\(?:ref|autoref|eqref)\{([^}]*)\}", src):
    if m.group(1) not in labels:
        # Tables live in \input files, whose labels are declared in the fallback
        # list below rather than in this file.
        if not m.group(1).startswith(("tab:", "fig:")):
            problems.append(f"\\ref{{{m.group(1)}}} has no matching \\label")
GENERATED_LABELS = {"tab:main_retrieval", "tab:alpha_policies", "tab:alpha_predictability",
                    "tab:attack_defense", "tab:utility_cost", "tab:behavioural_gap",
                    "tab:cost"}
for m in re.finditer(r"\\ref\{(tab:[^}]*)\}", src):
    if m.group(1) not in labels and m.group(1) not in GENERATED_LABELS:
        problems.append(f"\\ref{{{m.group(1)}}}: no \\label here and NB6 does not emit it")

# ----------------------------------------------------------------- macros
declared = {m.group(1) for m in
            re.finditer(r"\\(?:new|provide|renew)command\{\\(\w+)\}", src)}
KNOWN = {
    # LaTeX / package control sequences we are not going to enumerate exhaustively
    "documentclass", "usepackage", "title", "author", "name", "email", "addr", "def",
    "month", "year", "openreview", "begin", "end", "maketitle", "section", "subsection",
    "paragraph", "textbf", "textit", "emph", "texttt", "textcolor", "url", "cite",
    "citep", "citet", "label", "ref", "input", "includegraphics", "caption", "centering",
    "small", "toprule", "midrule", "bottomrule", "addlinespace", "multicolumn", "multirow",
    "appendix", "bibliographystyle", "bibliography", "item", "IfFileExists", "providecommand",
    "newcommand", "alpha", "star", "leq", "geq", "times", "setminus", "cup", "in", "text",
    "mid", "sim", "epsilon", "max", "min", "ldots", "PENDING", "bf", "it", "hline",
    "tilde", "s", "left", "right", "frac", "sum", "log", "quad", "qquad", "footnote",
    "textwidth", "columnwidth", "linewidth", "\\", "_", "&", "%", "$", "#", "{", "}",
}
used = {m.group(1) for m in re.finditer(r"\\([A-Za-z]+)", src)}
for name in sorted(used - declared - KNOWN):
    if name.islower() and len(name) <= 4:
        continue          # very likely a math or package command
    if re.match(r"^[a-z]+[A-Z]", name):    # our macros are camelCase
        problems.append(f"\\{name} looks like a result macro but is not declared "
                         f"in the fallback block")

# --------------------------------------------------------------- structure
depth, line_no = 0, 0
for i, line in enumerate(src.splitlines(), 1):
    for j, ch in enumerate(line):
        if j and line[j - 1] == "\\":
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth < 0:
                problems.append(f"line {i}: closing brace with no opener")
                depth = 0
    line_no = i
if depth:
    problems.append(f"braces unbalanced at end of file: {depth} unclosed")

envs = []
for m in re.finditer(r"\\(begin|end)\{(\w+\*?)\}", src):
    if m.group(1) == "begin":
        envs.append(m.group(2))
    else:
        if not envs:
            problems.append(f"\\end{{{m.group(2)}}} with no matching \\begin")
        elif envs[-1] != m.group(2):
            problems.append(f"\\end{{{m.group(2)}}} closes \\begin{{{envs[-1]}}}")
            envs.pop()
        else:
            envs.pop()
for e in envs:
    problems.append(f"\\begin{{{e}}} is never closed")

# --------------------------------------------------- placeholders remaining
pend = len(re.findall(r"\\PENDING", raw)) - raw.count("providecommand{\\PENDING}")
if not (TEX.parent / "results_macros.tex").exists():
    notes.append("results_macros.tex is absent, so every result macro will render "
                 "as a red placeholder. Run NB6 and copy it next to the .tex.")

# ------------------------------------------------------------------ report
print(f"checked {TEX}  ({line_no} lines, {len(cited)} citations, {len(labels)} labels)\n")
if notes:
    print("notes:")
    for n in notes:
        print("   ", n)
    print()
if problems:
    print(f"{len(problems)} problem(s):")
    for p in problems:
        print("   ", p)
    sys.exit(1)
print("no problems found")
